/* Arnux app registry: add a new app here, then openApp('your-id') will work. */
const APPS={
 browser:{name:'Browser',icon:'◎',color:'#2e5bff',render:browserApp},
 files:{name:'Files',icon:'▧',color:'#e85d2a',render:filesApp},
 terminal:{name:'Terminal',icon:'›_',color:'#161a17',render:terminalApp},
 notes:{name:'Notes',icon:'✎',color:'#d7a516',render:notesApp},
 store:{name:'ArnuxStore',icon:'▦',color:'#8d55e8',render:storeApp}
};
const HOME='/home/guest', FS_KEY='arnux-os-fs';
const seed={'/home/guest':{type:'dir'},'/home/guest/Documents':{type:'dir'},'/home/guest/Downloads':{type:'dir'},'/home/guest/README.md':{type:'file',content:'Welcome to Arnux OS.\n\nYour local files live in this browser.\n'},'/home/guest/welcome.txt':{type:'file',content:'Welcome home! Open ArnuxStore to discover more apps.\n'},'/tmp':{type:'dir'},'/etc':{type:'dir'},'/usr':{type:'dir'}};
let fs=JSON.parse(localStorage.getItem(FS_KEY)||'null')||seed;let currentDir=HOME;let z=10;let installed=JSON.parse(localStorage.getItem('arnux-installed')||'null')||['browser','files','terminal','notes','store'];let notes=JSON.parse(localStorage.getItem('arnux-notes')||'null')||[{title:'Welcome to Arnux',body:'This is your local Notes app.\nEverything is saved in your browser.'}];
const $=s=>document.querySelector(s);const save=()=>{localStorage.setItem(FS_KEY,JSON.stringify(fs));localStorage.setItem('arnux-installed',JSON.stringify(installed));localStorage.setItem('arnux-notes',JSON.stringify(notes))};
function path(p){if(!p||p==='~')return HOME;if(p.startsWith('~/'))p=HOME+p.slice(1);if(!p.startsWith('/'))p=currentDir+'/'+p;return('/'+p.split('/').filter(Boolean).reduce((a,x)=>x==='..'?a.slice(0,-1):x==='.'?a:[...a,x],[]).join('/'))||'/'}
function kids(dir){let pre=dir==='/'?'/':dir+'/';return Object.keys(fs).filter(x=>x!==dir&&x.startsWith(pre)&&!x.slice(pre.length).includes('/')).sort()}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function updateClock(){let d=new Date();let time=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});$('#topTime').textContent=time;$('#dockDate').textContent=d.toLocaleDateString([], {weekday:'short',month:'short',day:'numeric'})+' · '+time}setInterval(updateClock,1000);updateClock();
function openApp(id){if(!APPS[id])return;$('#launcherMenu').classList.remove('open');let existing=document.querySelector(`[data-window="${id}"]`);if(existing){existing.classList.remove('minimized');existing.style.zIndex=++z;return}let win=document.createElement('section');win.className='window';win.dataset.window=id;win.style.zIndex=++z;win.innerHTML=`<div class="window-bar"><div class="window-app"><span style="background:${APPS[id].color}">${APPS[id].icon}</span>${APPS[id].name}</div><div class="window-actions"><button data-min>−</button><button data-max>□</button><button data-close>×</button></div></div><div class="window-content"></div>`;$('#workspace').append(win);win.querySelector('.window-content').innerHTML=APPS[id].render();wireWindow(win,id);win.addEventListener('mousedown',()=>win.style.zIndex=++z)}
function wireWindow(win,id){win.querySelector('[data-close]').onclick=()=>win.remove();win.querySelector('[data-min]').onclick=()=>win.classList.toggle('minimized');win.querySelector('[data-max]').onclick=()=>win.classList.toggle('maximized');win.querySelector('.window-bar').ondblclick=()=>win.classList.toggle('maximized');if(id==='browser')wireBrowser(win);if(id==='files')wireFiles(win);if(id==='terminal')wireTerminal(win);if(id==='notes')wireNotes(win);if(id==='store')wireStore(win)}
function browserApp(){return `<div class="browser"><div class="browser-nav"><button class="back">‹</button><button class="forward">›</button><button class="refresh">↻</button><input class="url" value="arnux://home"><button class="go">Go</button></div><div class="browser-page"></div></div>`}
function browserPage(url){let q=url.trim();if(!q||q==='arnux://home')return `<div class="browser-home"><div class="browser-mark">◎</div><h2>Arnux Browser</h2><p>A private browser for the local web.</p><div class="search-row"><input class="search" placeholder="Search Arnux pages"/><button class="search-go">Search</button></div><div class="browser-links"><button data-url="arnux://files">Local Files</button><button data-url="arnux://store">ArnuxStore</button><button data-url="arnux://about">About Arnux</button></div></div>`;if(q==='arnux://files')return `<div class="internal-page"><span class="page-kicker">LOCAL WEB</span><h2>Files</h2><p>Your files stay inside this browser. Open the Files app to manage them.</p><button class="primary" data-launch="files">Open Files</button></div>`;if(q==='arnux://store')return `<div class="internal-page"><span class="page-kicker">APP DIRECTORY</span><h2>ArnuxStore</h2><p>Discover apps made for the Arnux desktop.</p><button class="primary" data-launch="store">Browse Store</button></div>`;if(q==='arnux://about')return `<div class="internal-page"><span class="page-kicker">ABOUT</span><h2>Arnux OS</h2><p>A full browser operating system built with local-first web technology.</p></div>`;return `<div class="internal-page"><span class="page-kicker">SEARCH RESULT</span><h2>${esc(q)}</h2><p>Arnux Browser only opens internal pages, so your browsing stays local and private.</p></div>`}
function wireBrowser(win){let page=win.querySelector('.browser-page'),url=win.querySelector('.url');const go=()=>{url.value=url.value||'arnux://home';page.innerHTML=browserPage(url.value);page.querySelectorAll('[data-url]').forEach(b=>b.onclick=()=>{url.value=b.dataset.url;go()});page.querySelectorAll('[data-launch]').forEach(b=>b.onclick=()=>openApp(b.dataset.launch));let s=page.querySelector('.search');if(s){page.querySelector('.search-go').onclick=()=>{url.value=s.value||'arnux://home';go()};s.addEventListener('keydown',e=>{if(e.key==='Enter'){url.value=s.value||'arnux://home';go()}})}};win.querySelector('.go').onclick=go;url.addEventListener('keydown',e=>{if(e.key==='Enter')go()});win.querySelector('.back').onclick=()=>{url.value='arnux://home';go()};win.querySelector('.refresh').onclick=go;go()}
function filesApp(){return `<div class="files-app"><aside class="file-sidebar"><button class="active">▧ All files</button><button>⌂ Home</button><button>▣ Documents</button><button>⇩ Downloads</button><div class="storage"><span>Local storage</span><div><i></i></div><small>12 KB used</small></div></aside><div class="file-main"><div class="file-toolbar"><button class="new-file">＋ New</button><span class="file-path">/home/guest</span></div><div class="file-grid"></div></div></div>`}
function wireFiles(win){let grid=win.querySelector('.file-grid');const render=()=>{grid.innerHTML=kids(currentDir).map(p=>`<button class="file-card" data-path="${esc(p)}"><span class="file-icon ${fs[p].type}">${fs[p].type==='dir'?'▰':'▤'}</span><b>${esc(p.split('/').pop())}</b><small>${fs[p].type==='dir'?'Folder':'File'}</small></button>`).join('')||'<div class="empty">This folder is empty.</div>';grid.querySelectorAll('[data-path]').forEach(b=>b.ondblclick=()=>{let p=b.dataset.path;if(fs[p].type==='dir'){currentDir=p;render()}else openEditor(p)})};win.querySelector('.new-file').onclick=()=>{let name=prompt('File name','untitled.txt');if(name){fs[path(name)]={type:'file',content:''};save();render()}};render()}
function notesApp(){return `<div class="notes-app"><aside class="notes-list"><button class="new-note">＋ New note</button><div class="note-items"></div></aside><div class="note-editor"><input class="note-title" placeholder="Note title"><textarea class="note-body" placeholder="Start writing..."></textarea><div class="note-save">Saved locally</div></div></div>`}
function wireNotes(win){let list=win.querySelector('.note-items'),title=win.querySelector('.note-title'),body=win.querySelector('.note-body'),active=0;const render=()=>{list.innerHTML=notes.map((n,i)=>`<button class="note-item ${i===active?'selected':''}" data-i="${i}"><b>${esc(n.title||'Untitled')}</b><small>${esc((n.body||'').split('\n')[0])}</small></button>`).join('');title.value=notes[active]?.title||'';body.value=notes[active]?.body||'';list.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{active=+b.dataset.i;render()})};const sync=()=>{notes[active]={title:title.value,body:body.value};save();win.querySelector('.note-save').textContent='Saved locally · '+new Date().toLocaleTimeString()};win.querySelector('.new-note').onclick=()=>{notes.unshift({title:'Untitled note',body:''});active=0;save();render()};title.oninput=body.oninput=sync;render()}
function storeApp(){return `<div class="store-app"><div class="store-hero"><span class="store-icon">▦</span><div><span class="page-kicker">ARNVX SOFTWARE</span><h2>ArnuxStore</h2><p>Small, focused apps for your desktop.</p></div></div><div class="store-grid">${Object.entries(APPS).filter(([id])=>id!=='store').map(([id,a])=>`<article class="store-card"><span class="app-big" style="background:${a.color}">${a.icon}</span><div><h3>${a.name}</h3><p>${id==='notes'?'Simple local notes with autosave.':id==='browser'?'Private internal browser for Arnux pages.':id==='files'?'Manage your local browser filesystem.':'A capable Linux-style shell.'}</p><button class="install" data-install="${id}">${installed.includes(id)?'Open':'Get'}</button></div></article>`).join('')}</div><div class="developer-tip"><b>Build for Arnux</b><span>Add an entry to the <code>APPS</code> registry in <code>app.js</code> with a <code>render()</code> function. The window manager wires the rest.</span></div></div>`}
function wireStore(win){win.querySelectorAll('[data-install]').forEach(b=>b.onclick=()=>{let id=b.dataset.install;if(!installed.includes(id)){installed.push(id);save();b.textContent='Open'}else openApp(id)})}
function terminalApp(){return `<div class="term-app"><div class="term-output"><div class="term-banner">Arnux Terminal · local shell<br><span>Type <b>help</b> for commands. Files persist in this browser.</span></div></div><form class="term-form"><span class="term-prompt">guest@arnux:~$</span><input class="term-input" autocomplete="off" spellcheck="false"></form></div>`}
function terminalEngine(cmd,out){let a=cmd.trim().split(/\s+/),n=a.shift();const p=s=>{out.insertAdjacentHTML('beforeend',`<div>${esc(s)}</div>`)};const saveFs=()=>save();if(!n)return;if(n==='help')p('help  ls  cd  pwd  cat  touch  mkdir  rm  nano  clear  echo  node  npm  neofetch');else if(n==='pwd')p(currentDir);else if(n==='whoami')p('guest');else if(n==='date')p(new Date().toString());else if(n==='echo')p(a.join(' '));else if(n==='clear')out.innerHTML='';else if(n==='ls')p(kids(currentDir).map(x=>x.split('/').pop()+(fs[x].type==='dir'?'/':'')).join('  ')||'(empty)');else if(n==='cd'){let q=path(a[0]||'~');if(fs[q]?.type==='dir'){currentDir=q}else p('cd: no such directory')}else if(n==='cat'){let q=path(a[0]);p(fs[q]?.content||'cat: file not found')}else if(n==='touch'){a.forEach(x=>fs[path(x)]={type:'file',content:''});saveFs();p('') }else if(n==='mkdir'){a.forEach(x=>fs[path(x)]={type:'dir'});saveFs();p('')}else if(n==='rm'){a.forEach(x=>delete fs[path(x)]);saveFs();p('')}else if(n==='nano'){openEditor(path(a[0]||'untitled.txt'))}else if(n==='node'){p(a.join(' ').replace(/^[-]e\s+/,'').replace(/console\.log\((.*)\)/,'$1').replace(/^['"]|['"]$/g,''))}else if(n==='npm')p('npm 10.8.2 · browser package simulation');else if(n==='neofetch')p('Arnux OS\nBrowser runtime · localStorage filesystem\nShell: arnux');else if(n==='clear')out.innerHTML='';else p(`${n}: command not found`);}
function wireTerminal(win){let out=win.querySelector('.term-output'),form=win.querySelector('.term-form'),inp=win.querySelector('.term-input');form.onsubmit=e=>{e.preventDefault();let cmd=inp.value;out.insertAdjacentHTML('beforeend',`<div class="term-command"><span>guest@arnux:~$</span> ${esc(cmd)}</div>`);terminalEngine(cmd,out);inp.value='';out.parentElement.scrollTop=out.parentElement.scrollHeight};inp.focus()}
function openEditor(p){let m=$('#nanoModal'),a=$('#nanoEditor');$('#nanoTitle').textContent='Arnux Editor — '+p;a.value=fs[p]?.content||'';m.classList.add('open');a.focus();$('#nanoSave').onclick=()=>{fs[p]={type:'file',content:a.value};save();m.classList.remove('open');};$('#nanoCancel').onclick=()=>m.classList.remove('open')}
function renderLauncher(){let box=$('#launcherApps');box.innerHTML=Object.entries(APPS).filter(([id])=>installed.includes(id)).map(([id,a])=>`<button data-launcher="${id}"><span style="background:${a.color}">${a.icon}</span>${a.name}</button>`).join('');box.querySelectorAll('[data-launcher]').forEach(b=>b.onclick=()=>openApp(b.dataset.launcher))}
renderLauncher();document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openApp(b.dataset.open));$('#launcherButton').onclick=()=>$('#launcherMenu').classList.toggle('open');$('#powerButton').onclick=()=>alert('Arnux is running locally in this browser.');document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#nanoModal').classList.remove('open');$('#launcherMenu').classList.remove('open')}if((e.ctrlKey||e.metaKey)&&e.key==='l'){e.preventDefault();openApp('terminal')}});save();
