/* Generated by scripts/build-app-catalog.js. Do not edit by hand. */
window.ARNYX_APP_CATALOG = [
  {
    "id": "hello-arnux",
    "name": "Hello Arnux",
    "version": "1.0.0",
    "icon": "◆",
    "color": "#5778ff",
    "description": "A minimal example app for Arnux.",
    "permissions": [
      "storage"
    ],
    "dependencies": [],
    "changelog": [
      "Initial release"
    ],
    "path": "apps/hello-arnux"
  }
];
